server:
  port: 8088
  servlet:
    context-path: /upload

spring:
  application:
    name: jv-upload
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.203.128:3306/jiavideo?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: LxR52013141220
    # hikari连接池配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 15
      # 控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 空闲连接最大存活时间
      idle-timeout: 600000
      # 连接池母子
      pool-name: MyHikariCP
      # 池中连接的最大生命周期
      max-lifetime: 1800000
      # 连接过期时间
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 500MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5  #  从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    instance-info-replication-interval-seconds: 5 #  复制实例变化信息到eureka服务器所需要的时间间隔（s），默认为30秒
    initial-instance-info-replication-interval-seconds: 5 # 最初复制实例信息到eureka服务器所需的时间（s），默认为40秒

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jiavideo.entity

logging:
  level:
    com.jiavideo.business: debug

jv:
  file:
    path: F:\video\upload\image\
    domain: http://127.0.0.1:10010/file/admin/upload/u/

# oss
oss:
  accessKeyId: LTAI4Fz5d3U1SFEMDRocNVrk
  accessKeySecret: vS7kiqas1k29ApwY8FeIqFeTcieg7l
  endpoint: http://oss-cn-heyuan.aliyuncs.com
  bucket: jiavideo-course
  ossDomain: http://jiavideo-course.oss-cn-heyuan.aliyuncs.com/

# vod
vod:
  accessKeyId: LTAI4FzA5JSEvZ8ab4XzECM6
  accessKeySecret: FeMz61eE0FjyiuOGVZEX07EjOgFWWH