server:
  port: 10010

spring:
  application:
    name: jv-gateway
  redis:
    host: 192.168.203.128
    port: 6379
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1:8080"
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 360000
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
              - HEAD
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      # 路由转发
      routes:
        # 对应模块所在名称
        - id: jv-system
          # 对应模块url
          uri: lb://jv-system
          predicates:
          # 转发所添加的路径
            - Path=/system/user/**
          filters:
            - name: Login
              agrs: true
          # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=1
        # 对应模块所在名称
        - id: jv-business
          # 对应模块url
          uri: lb://jv-business
          predicates:
            # 转发所添加的路径
            - Path=/business/**
          filters:
            - name: Login
              agrs: true
        # 对应模块所在名称
        - id: jv-upload
          # 对应模块url
          uri: lb://jv-upload
          predicates:
            # 转发所添加的路径
            - Path=/file/admin/upload/**
          filters:
            - name: Login
              agrs: true
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2
              # 对应模块所在名称
        - id: jv-auth
          # 对应模块url
          uri: lb://jv-auth
          predicates:
            # 转发所添加的路径
            - Path=/user/admin/auth/**
          filters:
            - name: Login
              agrs: true
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5  #  从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    instance-info-replication-interval-seconds: 5 #  复制实例变化信息到eureka服务器所需要的时间间隔（s），默认为30秒
    initial-instance-info-replication-interval-seconds: 5 # 最初复制实例信息到eureka服务器所需的时间（s），默认为40秒

logging:
  level:
    com.jiavideo.gateway: debug
