server:
  port: 10010

spring:
  application:
    name: jv-gayeway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 360000
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
              - HEAD
      # 路由转发
      routes:
        # 对应模块所在名称
        - id: jv-system
          # 对应模块url
          uri: http://127.0.0.1:8086
          predicates:
          # 转发所添加的路径
            - Path=/system/**
         # filters:
          # 表示过滤1个路径，2表示两个路径，以此类推
           # - StripPrefix=1
        # 对应模块所在名称
        - id: jv-business
          # 对应模块url
          uri: lb://jv-business
          predicates:
            # 转发所添加的路径
            - Path=/business/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5  #  从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    instance-info-replication-interval-seconds: 5 #  复制实例变化信息到eureka服务器所需要的时间间隔（s），默认为30秒
    initial-instance-info-replication-interval-seconds: 5 # 最初复制实例信息到eureka服务器所需的时间（s），默认为40秒

logging:
  level:
    com.jiavideo.gateway: debug